development:  
  adapter: postgresql
  encoding: unicode
  database: Task
  pool: 5
  username: 12373
  password: 1234

test:  
  adapter: postgresql
  encoding: unicode
  database: Task
  pool: 5
  username: 12373
  password: 1234